---
title: 'Institutionalizing Success'
author: Jennifer M. Johnson & Jake D. Winfield
date: '2022-06-17'
slug: jhe-2022
categories:
  - Research
tags:
  - HBCUs
  - college student success
  - alumni
subtitle: 'Practices and Policies at HBCUs that Promote Student
  Development and Degree Attainment'
excerpt: ''
draft: no
series: ~
layout: single
---
In this [article](https://doi.org/10.1080/00221546.2022.2082759) published in the *Journal of Higher Education*, [Dr. Jennifer M. Johnson](https://www.jmjohnsonphd.com) and I analyze interviews with 20 alumni of twelve different Historically Black Colleges and Universities to highlight institutional practices students articulated were key to their success.  

## Abstract
A central purpose of Historically Black Colleges and Universities (HBCUs) is to educate Black students, often in conditions where resources, financial and otherwise, are limited. This study explores how institutional policies and practices foster success among Black students attending HBCUs within these conditions. Using an HBCU-based model for Black College Student Success, we examine the perceptions of institutional actions that promote success among 20 HBCU alumni. Through constructivist qualitative inquiry, we found evidence for each component of the model in the practices of institutional actors of the 12 institutions studied. We also found evidence of additional domains where practices at HBCUs promoted student success.

#### Citation
Johnson, J. M. & Winfield, J. D. (2022). Institutionalizing success: Practices and policies at HBCUs that promote student development and degree attainment. *Journal of Higher Education* Advance Online Publication. [https://doi.org/10.1080/00221546.2022.2082759]()

A PDF of this paper is available upon request.

The cover image from this paper was generated with [Tinkersynth](https://tinkersynth.com/) by Jake Winfield.
